Workaround to install dependencies before running rpm scriptlets
This change force RPM resolver to install bash dependencies on bash
install, to run non delayed scriptlets of other packages.

To make bash fully usable once package is installed, we add a stronger
requirement on dependencies is using "Requires(pre):" to prevent deps
(declared as "Requires:") to be installed later in the transaction,
this will make scriplets (depending on bash and its deps) runables
sonner.

Scriptlets are depending on "/bin/sh" as provided by bash which needs:

* filesystem: to provide /bin/sh link bash
* glibc: to provide runtime
* ncurses-compat-libs: to provide libtinfo.so.5 lib

We believe that when prevent dependencies loop the rpm resolver is
cutting some (weak) dependencies by ignoring some "Requires:".

The issues been observed using some packages, like ca-certificates,
p11-kit and probably more will trigger similar issues.

We supposed that cause of cycle is in xcp-ng-release but after a
couple of attempt of tweaking it, rebuild of p11-kit made of
rebuilding ca-certificates was still impossible.

Note that ca-certificates is also a package with circular dependency.

The real root cause might be then in RPM itself,
as confirmed in 2016 by upstream in rhbz#1402023:

  "We can't get rid of such dependency cycles unless RPM
  implements delayed script execution.
  With delayed script execution, scriptlets will only run
  after the dependencies have at least been unpacked."

This workaround is made in bash package to minimize propagation of the issue
(eg: this line could be added only in problematic packages (see Related links).

The following errors were observed in koji:

```
DEBUG util.py:461:    Running scriptlet: ca-certificates-2021.2.50-72.el7_9.noarch           14/142
DEBUG util.py:461:  error: failed to exec scriptlet interpreter /bin/sh: No such file or directory
DEBUG util.py:461:  error: %prein(ca-certificates-2021.2.50-72.el7_9.noarch) scriptlet failed, exit status 127
DEBUG util.py:459:  Error in PREIN scriptlet in rpm package ca-certificates

rpm -q --scripts   ca-certificates
preinstall scriptlet (using /bin/sh):
(...)
```
or

```
DEBUG util.py:461:    Running scriptlet: ca-certificates-2021.2.50-73~XCPNG2698.1.xcpng8.    35/142
DEBUG util.py:461:  /bin/sh: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
DEBUG util.py:461:  error: %prein(ca-certificates-2021.2.50-73~XCPNG2698.1.xcpng8.3.noarch) scriptlet failed, exit status 127
DEBUG util.py:459:  Error in PREIN scriptlet in rpm package ca-certificates
DEBUG util.py:461:    Installing       : openssl-libs-1:3.0.9-2.0.1.3.xcpng8.3.x86_64        36/142
DEBUG util.py:461:  error: ca-certificates-2021.2.50-73~XCPNG2698.1.xcpng8.3.noarch: install failed

```

Origin: https://github.com/xcp-ng-rpms/bash/pull/1
Related-to: XCPNG-3042
Related-to: https://bugzilla.redhat.com/show_bug.cgi?id=1402023
Related-to: https://github.com/xcp-ng-rpms/ca-certificates/pull/1#discussion_r2852198131
Related-to: https://github.com/xcp-ng-rpms/p11-kit/pull/1#pullrequestreview-3944953864
Signed-off-by: Philippe Coval <philippe.coval@vates.tech>